spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/coffeenotes
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        default_schema: coffeenotes
  flyway:
    enabled: true
    schemas: coffeenotes
    baseline-on-migrate: true
