spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/coffeenotes
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        default_schema: coffeenotes
  flyway:
    enabled: true
    schemas: coffeenotes
    default-schema: coffeenotes

logging:
  level:
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: DEBUG


app:
  security:
    cors:
      allowed-origins:
        - http://localhost:3000
    jwt:
      issuer: coffeenotes-api
      audience: coffeenotes-web
      private-key-location: file:../secrets/private_key.pem
      public-key-location: file:../secrets/public_key.pem
    cookie:
      secure: false